spring:
  application:
    name: identity-service


com:
  emerson:
    authserver:
      config:
        mfaEndpoints:
          Email: "/mfa/verifyEmailCode"
          Authenticator: "/mfa/verifyAuthenticatorCode"
